import {
  Component,
  OnInit
} from '@angular/core';

@Component({
  selector: 'app-game',
  templateUrl: './game.component.html',
  styleUrls: ['./game.component.scss']
})
export class GameComponent implements OnInit {

  started!: boolean;
  ended!: boolean;
  counter!: number;
  timeLeft!: number;
  timer!: number;
  word!: string;
  randomNbr!: number;
  timeGame!: number;

  constructor() {}

  ngOnInit(): void {}


  /**
   * Function to start the game, to initialize the variables
   * Call the function playGame()
   */
  startGame() {
    this.started = true;
    this.ended = false;
    this.counter = 0;
    // TimeGame is the maximum lap time of the game
    this.timeGame = 2000;
    // TimeLeft is used for the timer
    this.timeLeft = this.timeGame;
    // We call playGame() to generate the word and set the timer
    this.playGame();
  }


  // Function that generates words and manages the timer
  playGame(){
    // We clear the interval
    window.clearInterval(this.timer);
    // Every time playGame() is called, the timeLeft will have the timeGame value
    this.timeLeft = this.timeGame;
    // We generate a random number that will be 1 or 0, this will help us to know if we generate a word or a palindrome
    this.randomNbr = this.getRandom(0, 1);
    //getWord(nbr) is used to generate a random word
    this.word = this.getWord(this.randomNbr);
    //Set interval
    this.timer = window.setInterval(() => {
      this.timeLeft = this.timeLeft - 5;
      if (this.timeLeft === 0) {
        window.clearInterval(this.timer);
        this.ended = true;
      }
    }, 1);
  }

  // To count the score
  countClick() {
    if (!this.ended) {
      this.counter++;
    }
  }

  // To add a random number between two numbers
  getRandom(min: number, max: number) {
    return Math.floor(Math.random() * (max - min + 1)) + min;
  }

  /**
   * Function to generate a non-palindrome word
   * Note for Thomas Pierre Toledo: We've decided to put too parameters, to choose the min and max caracters of the words that will be generated 
   * That's because we used that function then to create palindromes to avoid having duplicate code. 
   * So we can't set the getRandom's parameters inside the function because the palindromus would be much larger than the normal words.
   * @param min 
   * @param max
   * @returns word : the final word generated by the function
   */
  generateWord(min: number, max: number) {
    const vowels = 'aeiouy'.split('');
    const consonnants = 'bcdfghjklmnpqrstvwxz'.split('');
    const randomNbr = this.getRandom(min, max);

    let word = '';

    for (let i = 0; i < randomNbr; i++) {
      if (i % 2 === 0) {
        word += vowels[Math.floor(Math.random() * (vowels.length - 1))];
      } else {
        word += consonnants[Math.floor(Math.random() * (consonnants.length - 1))]
      }
    }

    return word;
  }

  // To generate a palindrome, using the generateWord() function
  generatePalindrome() {
    let palindrome = this.generateWord(2, 8);
    let splitPalindrome = palindrome.split('');
    let reversePalindrome = splitPalindrome.reverse();
    let joinPalindrome = reversePalindrome.join('');

    return palindrome + joinPalindrome;
  }

  // To get a random word between generateWord and generatePalindrome.
  getWord(nbr: number) {
    // If the random number is 0, so we call the generateWord function
    if (nbr === 0) {
      return this.generateWord(4, 16);
    } else { // If not, we generate a palindrome
      return this.generatePalindrome();
    }
  }

  // Function to manage the yes button of the game
  yesButton() {
    // If the word is not a palindrome
    if (this.randomNbr === 0) {
      // End of the game and we clear the Interval
      this.ended = true;
      window.clearInterval(this.timer);
    } else {
      // We count a point
      this.counter++;
      // We call playGame() to generate a new word and set again the interval
      this.playGame();
      if(this.counter%5 === 0){
        // To keep the time Game at 300ms
        if(this.timeGame === 300){
          this.timeGame = 300;
          // to reduce the time of -100ms every 5 good answers
        } else if(this.timeGame > 300) {
          this.timeGame = this.timeGame - 100;
        }
      }
    } 
  }

  // Function to manage the no button of the game. The logic is the same as the yesButton
  noButton() {
    if (this.randomNbr === 0) {
      this.counter++;
      this.playGame();
      if(this.counter%5 === 0){
        if(this.timeGame === 300){
          this.timeGame = 300;
        } else {
          this.timeGame = this.timeGame - 100;
        }
      }
    } else {
      this.ended = true;
      window.clearInterval(this.timer);
    }
  }

}
